## NBA Shot Selection Prediction

## Business Understanding

Kobe Bryant, one of the greatest basketball players in history, played 20 seasons with the Los Angeles Lakers. Over his career, he took thousands of shots in varying game situations — from buzzer-beaters to playoff clutch moments. Understanding the context and success rate of these shots can offer powerful insights for sports analysts, coaches, and players.

In this project, we analyze the **complete dataset of Kobe Bryant’s shot attempts** to identify patterns that lead to successful or missed shots. The ultimate goal is to **build a machine learning model** that can predict whether a shot is likely to be successful based on game and shot conditions.

##  Dataset Overview

The dataset contains detailed information about **every field goal attempt Kobe Bryant took** during his 20-year NBA career. It includes features like:

- **Game context**: period, time remaining, opponent, playoffs
- **Shot context**: location (x, y, lat, lon), shot distance, shot type, zone
- **Game info**: season, matchup, home/away
- **Target variable**: `shot_made_flag` (0 or 1)

> Total rows: ~30,000 | Features: 25+ | Domain: **Sports Analytics**

## What is `shot_made_flag`?

- **`shot_made_flag` = 1**: The shot was **made** (successful)
- **`shot_made_flag` = 0**: The shot was **missed**
- This is the **target variable** for prediction.

## Problem Type

This is a **Supervised Binary Classification Problem**.

We will use machine learning algorithms to **predict whether a shot will be made (1) or missed (0)** based on the features describing the shot and the game situation.

## The objective is to:
- Analyze Kobe Bryant’s shot data using visual analytics.
- Help stakeholders understand shot selection patterns.
- Predict the probability of a successful shot using machine learning.

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.io as pio
pio.renderers.default = 'notebook' 
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV, StratifiedKFold
import shap

In [3]:
#loading the dataset
data = pd.read_csv('C:/Users/arbaj/Projects/NBA Shot Predictions/data/data.csv')

In [4]:
#first 5 rows of the data
data.head()

,action_type,combined_shot_type,game_event_id,game_id,lat,loc_x,loc_y,lon,minutes_remaining,period,...,shot_type,shot_zone_area,shot_zone_basic,shot_zone_range,team_id,team_name,game_date,matchup,opponent,shot_id
0,Jump Shot,Jump Shot,10,20000012,33.9723,167,72,-118.1028,10,1,...,2PT Field Goal,Right Side(R),Mid-Range,16-24 ft.,1610612747,Los Angeles Lakers,2000-10-31,LAL @ POR,POR,1
1,Jump Shot,Jump Shot,12,20000012,34.0443,-157,0,-118.4268,10,1,...,2PT Field Goal,Left Side(L),Mid-Range,8-16 ft.,1610612747,Los Angeles Lakers,2000-10-31,LAL @ POR,POR,2
2,Jump Shot,Jump Shot,35,20000012,33.9093,-101,135,-118.3708,7,1,...,2PT Field Goal,Left Side Center(LC),Mid-Range,16-24 ft.,1610612747,Los Angeles Lakers,2000-10-31,LAL @ POR,POR,3
3,Jump Shot,Jump Shot,43,20000012,33.8693,138,175,-118.1318,6,1,...,2PT Field Goal,Right Side Center(RC),Mid-Range,16-24 ft.,1610612747,Los Angeles Lakers,2000-10-31,LAL @ POR,POR,4
4,Driving Dunk Shot,Dunk,155,20000012,34.0443,0,0,-118.2698,6,2,...,2PT Field Goal,Center(C),Restricted Area,Less Than 8 ft.,1610612747,Los Angeles Lakers,2000-10-31,LAL @ POR,POR,5

In [5]:
#last 5 rows of the data
data.tail()

,action_type,combined_shot_type,game_event_id,game_id,lat,loc_x,loc_y,lon,minutes_remaining,period,...,shot_type,shot_zone_area,shot_zone_basic,shot_zone_range,team_id,team_name,game_date,matchup,opponent,shot_id
30692,Jump Shot,Jump Shot,397,49900088,33.9963,1,48,-118.2688,6,4,...,2PT Field Goal,Center(C),In The Paint (Non-RA),Less Than 8 ft.,1610612747,Los Angeles Lakers,2000-06-19,LAL vs. IND,IND,30693
30693,Tip Shot,Tip Shot,398,49900088,34.0443,0,0,-118.2698,6,4,...,2PT Field Goal,Center(C),Restricted Area,Less Than 8 ft.,1610612747,Los Angeles Lakers,2000-06-19,LAL vs. IND,IND,30694
30694,Running Jump Shot,Jump Shot,426,49900088,33.8783,-134,166,-118.4038,3,4,...,2PT Field Goal,Left Side Center(LC),Mid-Range,16-24 ft.,1610612747,Los Angeles Lakers,2000-06-19,LAL vs. IND,IND,30695
30695,Jump Shot,Jump Shot,448,49900088,33.7773,31,267,-118.2388,2,4,...,3PT Field Goal,Center(C),Above the Break 3,24+ ft.,1610612747,Los Angeles Lakers,2000-06-19,LAL vs. IND,IND,30696
30696,Jump Shot,Jump Shot,471,49900088,33.9723,1,72,-118.2688,0,4,...,2PT Field Goal,Center(C),In The Paint (Non-RA),Less Than 8 ft.,1610612747,Los Angeles Lakers,2000-06-19,LAL vs. IND,IND,30697

In [6]:
#basic information
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30697 entries, 0 to 30696
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   action_type         30697 non-null  object
 1   combined_shot_type  30697 non-null  object
 2   game_event_id       30697 non-null  int64
 3   game_id             30697 non-null  int64
 4   lat                 30697 non-null  float64
 5   loc_x               30697 non-null  int64
 6   loc_y               30697 non-null  int64
 7   lon                 30697 non-null  float64
 8   minutes_remaining   30697 non-null  int64
 9   period              30697 non-null  int64
 10  playoffs            30697 non-null  int64
 11  season              30697 non-null  object
 12  seconds_remaining   30697 non-null  int64
 13  shot_distance       30697 non-null  int64
 14  shot_made_flag      25697 non-null  float64
 15  shot_type           30697 non-null  object
 16  shot_zone_area      30697 non-null  object
 17  shot_zone_basic     30697 non-null  object
 18  shot_zone_range     30697 non-null  object
 19  team_id             30697 non-null  int64
 20  team_name           30697 non-null  object
 21  game_date           30697 non-null  object
 22  matchup             30697 non-null  object
 23  opponent            30697 non-null  object
 24  shot_id             30697 non-null  int64
dtypes: float64(3), int64(11), object(11)
memory usage: 5.9+ MB